### ISSUE TITLE
Create an Offline installer since Unowhy PC's lock the admin account from the organisation strategy. 

### ISSUE THREAD

**Issue by TiagonewDEV** [STY1001/Unowhy-Tools#1]
My friend did not turned on her computer so she can still install unowhy tools and disconnect from the azureAD. But i can not managed to install Unowhy tool offline... And if i connect the pc to the internet, the pc is gonna disable the administrator account by himself...

**Comment by STY1001** [comment]
Hello, for this probleme, you need to turn off HiSqool Manager and disconnect AzureAD
You can use a temporaly solution:
- Download this: https://github.com/STY1001/Unowhy-Tools/blob/master/Archive/UT17.0.zip
- Extract it, in a folder
- And launch "unowhy tools.exe"

**Comment by TiagonewDEV** [comment]
Ok thank you ! I'll try when i'm home ;)

**Comment by STY1001** [comment]
Hello, I release an offline installer 
You can download it here:
https://github.com/STY1001/Unowhy-Tools/releases/download/v17.0/Unowhy.Tools.17.0.Installer.exe
