### ISSUE TITLE
Désinstallation de "HiSqoolManager" marqué comme "avec erreur(s)" mais bien désinstallé  

### ISSUE THREAD

**Issue by KenzLeVrai** [STY1001/Unowhy-Tools#12]
Version : 27.01
Version de l'OS : Windows 11 Professionnel Education 23H2 22631.3155 (Feature Experience Pack 1000.22684.1000.0)
Année de l'ordinateur : 2023

Tout est dans le titre, le logiciel ainsi que le raccourci est bien supprimé mais apparemment UT n'arrive pas à détecter la désinstallation.

**Comment by STY1001** [comment]
Salut,
J'ai remarqué ce bug, enfaite l'uninstaller de HiSqool ne supprime plus le dossier HiSqool, je ne sais pas pourquoi.
Mais Unowhy Tools justement détermine s'il est installé ou pas grâce à ça, mais ouai, ça sera fix dans la 28.00

**Comment by KenzLeVrai** [comment]
Nickel alors, je close
