### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by Nemi04** [STY1001/Unowhy-Tools#14]
Petits problèmes au niveau de l'interface (en rouge)
![image](https://github.com/STY1001/Unowhy-Tools/assets/84980479/d6aa0876-0a48-4fb2-8db0-ebe64a60ff82)

**Comment by STY1001** [comment]
Pour le titre, ça, je n'y peux rien, ça correspond au design system de Windows 11
Par contre, cacher la taille des logs, c'est un peu abusé 😂

**Comment by Nemi04** [comment]
ouais je sais pas j'me suis dit "au cas où" 😂

**Comment by Nemi04** [comment]
voici la suite, entre personnalis et hisqool ma y'a de très jolies icones
![image](https://github.com/STY1001/Unowhy-Tools/assets/84980479/40fb8d62-8b21-410a-9167-7447637ce5a2)
