### ISSUE TITLE
Connecté sans accès à internet

### ISSUE THREAD

**Issue by tcherno78** [STY1001/Unowhy-Tools#18]
Bonjour, j'ai utilisé vos outils pour être admin sur mon pc idf y13gen2.
La procédure a bien fonctionné,MERCI! mais je n'ai plus accès au réseau internet du lycée.
Le PC se connecte bien mais le wifi indique "connecté sans accès à internet".
Pouvez-vous m'aider svp ?

**Comment by STY1001** [comment]
Bonjour
Pour obtenir de l'aide pour votre Y13
Veuillez utiliser le [Discord](https://discord.gg/dw3ZJ9u7WS)
Merci

**Comment by Kofysh** [comment]
![verification_icon](https://github.com/user-attachments/assets/405e65ef-a22b-44b2-a444-020d36bb7e21)
