### ISSUE TITLE
Une version pour linux ?

### ISSUE THREAD

**Issue by Qwertykiller2009** [STY1001/Unowhy-Tools#19]
Bonjour, est-ce qu'il y a une version pour Arch Linux ?

**Comment by Syxpi** [comment]
Je réponds a sa place: Nan. Car les drivers Arch pour les Y13 n'existent pas en grande partie. 

Et surtout, STY n'as pas prévu de faire du dev Linux (Shell Script, C++, C, Python ou autre)

Et UT pour les Y13 sur Linux,c usless je trouve,car 95% des fonctionnalités sont based Windows

**Comment by STY1001** [comment]
Ah bah très bon résumé mdrr
Sur Linux l'app n'a 0 intérêt 
95% des fonctionnalités sont du Windows only, et les drivers bah c'est pas comme sur windows, et de toute facon si ca marche pas, bah juste RIP, tu peut pas y faire grand chose
Alors après il y a bien du C# sur Linux mais bon je vais juste me faire insulter

**Comment by Syxpi** [comment]
> Ah bah très bon résumé mdrr
> Sur Linux l'app n'a 0 intérêt 
> 95% des fonctionnalités sont du Windows only, et les drivers bah c'est pas comme sur windows, et de toute facon si ca marche pas, bah juste RIP, tu peut pas y faire grand chose
> Alors après il y a bien du C# sur Linux mais bon je vais juste me faire insulter 

En soit oui y'as du C# pour Linux, mais c'est une horreur a faire tourner. 

Surtout que si tu fais l'app sur Linux,a quoi sa va servir ? Tu va modif l'hostname? Tu fais 3 commandes et c bon. 

Et justement,les drivers, surtout sur Arch,sont inexistant en soit. 
Même Ubuntu 24 tu en a quasi pas. Peut être sur les Y13 2023+ sa a changé,mais sur les 2022 et moins,on a rien

**Comment by STY1001** [comment]
Le Y13 Gen 2 2024 c'est le même delire niveau drivers, on change pas une équipe qui perd mdrrr
Bon en soit faut faire des tests de plein de distrib Linux sur sont propre Y13, avec le kernel le plus récent de préférence

**Comment by Syxpi** [comment]
> Le Y13 Gen 2 2024 c'est le même delire niveau drivers, on change pas une équipe qui perd mdrrr
> Bon en soit faut faire des tests de plein de distrib Linux sur sont propre Y13, avec le kernel le plus récent de préférence 

Je sais que pendant un moment,je testait plein d'OS sur mon Y13 perso, stv j'peut le refaire. Tu m'en parle en DM Discord et on voit sa

**Comment by STY1001** [comment]
> > Le Y13 Gen 2 2024 c'est le même delire niveau drivers, on change pas une équipe qui perd mdrrr
> > Bon en soit faut faire des tests de plein de distrib Linux sur sont propre Y13, avec le kernel le plus récent de préférence
> 
> Je sais que pendant un moment,je testait plein d'OS sur mon Y13 perso, stv j'peut le refaire. Tu m'en parle en DM Discord et on voit sa

Après ce qui est con, c'est que c'est assez spécifique à chaque Y13 (ou groupe de Y13), car parfois, il y a des mini variations qui casse tout. Surtout les versions 2022 et avant
C'est cool d'avoir fait ça, mais malheureusement, c'est une liste d'os qui marche qui ne s'applique pas à tout le monde.

**Comment by Syxpi** [comment]
> > > Le Y13 Gen 2 2024 c'est le même delire niveau drivers, on change pas une équipe qui perd mdrrr
> > > Bon en soit faut faire des tests de plein de distrib Linux sur sont propre Y13, avec le kernel le plus récent de préférence
> > 
> > 
> > Je sais que pendant un moment,je testait plein d'OS sur mon Y13 perso, stv j'peut le refaire. Tu m'en parle en DM Discord et on voit sa
> 
> Après ce qui est con, c'est que c'est assez spécifique à chaque Y13 (ou groupe de Y13), car parfois, il y a des mini variations qui casse tout. Surtout les versions 2022 et avant C'est cool d'avoir fait ça, mais malheureusement, c'est une liste d'os qui marche qui ne s'applique pas à tout le monde.

après sa peut voir que avec genre un Y13 t'as tel OS qui fonctionne, 
sachant que j'accepte la contribution des gens pour ceci

donc au moins on aura une liste de compatibilité

**Comment by Kofysh** [comment]
Exact !
