### ISSUE TITLE
Suggestion : version portable

### ISSUE THREAD

**Issue by Nostres25** [STY1001/Unowhy-Tools#8]
Bonjour bonjour ! N'ayant pas beaucoup d'espace sur le piti Y13, je me dis qu'une version portable de l'unowhy tool qu'on peut mettre sur une clé USB comme je le fait avec beaucoup de logiciels serait sympa :D

**Comment by STY1001** [comment]
Salut
Ce n'est pas une mauvaise idée, mais au vu de la complexité du fonctionnement de Unowhy Tools, notamment avec UTS, ça va être très compliqué de port l'app en portable, après l'app ne pèse qu'une centaine de Mo
Mais ce n'est pas une mauvaise suggestion

**Comment by azgaresncf** [comment]
> Salut Ce n'est pas une mauvaise idée, mais au vu de la complexité du fonctionnement de Unowhy Tools, notamment avec UTS, ça va être très compliqué de port l'app en portable, après l'app ne pèse qu'une centaine de Mo Mais ce n'est pas une mauvaise suggestion

Il faut simplement uploader `install.zip`, qui contient le dit-logiciel en version portable

**Comment by azgaresncf** [comment]
Bizarre, sachant que personnellement, il ne le flag JAMAIS

**Comment by Nemi04** [comment]
Pour faire une version portable, il faudrait limiter les fonctionnalités de l'app Unowhy Tools Portable à ce qui est toléré afin de ne pas déclencher l'Antivirus.

**Comment by STY1001** [comment]
Même une application vide se fait détecter comme un malware donc bon

**Comment by Nemi04** [comment]
wow

**Comment by Kofysh** [comment]
> Salut Ce n'est pas une mauvaise idée, mais au vu de la complexité du fonctionnement de Unowhy Tools, notamment avec UTS, ça va être très compliqué de port l'app en portable, après l'app ne pèse qu'une centaine de Mo Mais ce n'est pas une mauvaise suggestion

C'est possible de le faire, du moment que toute les librairies DLL et les fichiers sont ensemble ça fonctionnnera sans problème.

**Comment by Kofysh** [comment]
> Pour faire une version portable, il faudrait limiter les fonctionnalités de l'app Unowhy Tools Portable à ce qui est toléré afin de ne pas déclencher l'Antivirus.

Il suffira simplement de signer cryptographiquement l'éxécutable ;)

**Comment by Syxpi** [comment]
> > Pour faire une version portable, il faudrait limiter les fonctionnalités de l'app Unowhy Tools Portable à ce qui est toléré afin de ne pas déclencher l'Antivirus.
> 
> Il suffira simplement de signer cryptographiquement l'éxécutable ;)

je réponds 2 semaines après:

en soit c'est possible,mais sa coute cher de faire ceci, on pourrait le faire gratuitement,mais faudra installer le certificat manuellement sur son pc, ce qui n'est pas intéressant du tout.

donc si STY a entre 200 et 300€ a foutre dans une license par mois, c'est parfait. sinon,c'est mort

**Comment by Kofysh** [comment]
En aucun cas n

> > > Pour faire une version portable, il faudrait limiter les fonctionnalités de l'app Unowhy Tools Portable à ce qui est toléré afin de ne pas déclencher l'Antivirus.
> > 
> > 
> > Il suffira simplement de signer cryptographiquement l'éxécutable ;)
> 
> je réponds 2 semaines après:
> 
> en soit c'est possible,mais sa coute cher de faire ceci, on pourrait le faire gratuitement,mais faudra installer le certificat manuellement sur son pc, ce qui n'est pas intéressant du tout.
> 
> donc si STY a entre 200 et 300€ a foutre dans une license par mois, c'est parfait. sinon,c'est mort

Il est tout à fait possible de signer le logiciel en version portable en utilisant des outils gratuits. Tu peux utiliser Signtool, qui fait partie des kits de développement de Microsoft pour les signatures numériques sur Windows. Ca permet de signer l'exécutable sans avoir à acheter de certificat ^^

**Comment by Syxpi** [comment]
> > > > Pour faire une version portable, il faudrait limiter les fonctionnalités de l'app Unowhy Tools Portable à ce qui est toléré afin de ne pas déclencher l'Antivirus.
> > > 
> > > 
> > > Il suffira simplement de signer cryptographiquement l'éxécutable ;)
> > 
> > je réponds 2 semaines après:
> > 
> > en soit c'est possible,mais sa coute cher de faire ceci, on pourrait le faire gratuitement,mais faudra installer le certificat manuellement sur son pc, ce qui n'est pas intéressant du tout.
> > 
> > donc si STY a entre 200 et 300€ a foutre dans une license par mois, c'est parfait. sinon,c'est mort
> 
> Il est tout à fait possible de signer le logiciel en version portable en utilisant des outils gratuits. Tu peux utiliser Signtool, qui fait partie des kits de développement de Microsoft pour les signatures numériques sur Windows. Ca permet de signer l'exécutable sans avoir à acheter de certificat ^^

Oui mais non,car les certs gratuit c juste dans un environnement de dev, pas de prod.

Et signtool c only pour du dev.
Car les certs par signtool c'est pas émis depuis un CA officiel.

**Comment by STY1001** [comment]
Les programmes self signed sont flag par les AV

**Comment by Syxpi** [comment]
> Les programmes self signed sont flag par les AV

bah oui,car le self signed c used en dev.
tu peut pas le mettre en prod

**Comment by Kofysh** [comment]
Une révision du code est prévue très prochainement, donc il n'est pas nécessaire de développer une version portable pour l'instant

> > Les programmes self signed sont flag par les AV
> 
> bah oui,car le self signed c used en dev. tu peut pas le mettre en prod
