### ISSUE TITLE
Quelques petites suggestions

### ISSUE THREAD

**Issue by azgaresncf** [STY1001/Unowhy-Tools#9]
Salut ! 
Merci encore pour ce logiciel qui évolue de plus en plus en style (je trouve que la charte graphique est parfaite :D). Néanmoins, j'aimerais apporter quelques petites suggestions pour faire en sorte que le logiciel soit parfait (Attention: il ne s'agit que de mon avis personnel).

## 1) concernant l'installation + CLI
Pour les personnes qui souhaiteraient installer par défaut le logiciel (installation d'un OS par exemple) ou qui souhaiteraient simplement l'installer sans avoir besoin interaction humaine, il faudrait pouvoir créer un système d'installation "sans surveillance" (ou *unattended mode* en Anglais) comme un argument pour un potentiel CLI (exemple: ``setup.exe /unattended``).

Pourquoi pas aussi créer d'autres options de CLI comme ``/path`` pour désigner le chemin d'installation du programme.

Ensuite, serait-t-il plus judicieux de créer un ``install.zip`` au moment de la compilation du logiciel (``System.IO.Compression.ZipFile.CreateFromDirectory``), afin de pouvoir éviter de penser à le faire manuellement ?

Ensuite, comme pour l'issue #8, il faudrait pouvoir créer pour la compilation une installation portable et avec installateur.

Pour la compilation, pourquoi pas pouvoir utiliser les *GitHub Actions*, afin de pouvoir automatiser le processus de publication des versions ;)

Et enfin, serait-il judicieux de publier le logiciel dans des gestionnaires de paquets (tels que Chocolatey ?)

Je peux essayer de t'aider sur quelques trucs si jamais tu as besoin ;) 

## 2) dans le logiciel
Il faudrait pouvoir faire en sorte de créer un fichier du type "settings.json", afin de pouvoir faire en sorte de désactiver certaines options.

L'Edge Uninstaller me parait assez unsafe, il y a un script d'AveYo qui désinstalle très bien Edge. (https://rentry.org/uninstallmsedge)

**Comment by STY1001** [comment]
Salut
Alors pour le setup, il existe bien une mode Quiet avec "/s"
ensuite, effectivement, je mets manuellement le .zip dans le proj, bon le .zip est fait automatiquement avec un script .bat sur mon pc mdr, mais pour ton idée de l'add au compilé, c'est pas con, juste, bah comment faire mdr, je sais pas
Pour Github action, j'ai vu ce truc, mais vraiment, je suis une bille sur GitHub, t'as dû surement le remarquer mdr
Ensuite, pour le settings.json, ça j'ai pas trop compris, bon, je pense migrer les settings du registre vers un fichier, ça sera bien plus simple, pour éviter d'avoir des problèmes entre les comptes
Ensuite, pour le uninstall de Edge, c'est based sur le setup de Edge officiel, donc ça va c'est assez fiable

**Comment by azgaresncf** [comment]
> Alors pour le setup, il existe bien une mode Quiet avec "/s" 
Nickel tout ça ! Du coup, ça te dirait de le publier sur un package manger tel Chocolatey ou WinGet? Combiné aux github actions, cela pourrait permettre de faire une automisation des mises à jours du logiciel ! (si tu veux je peux le faire) ;)

> mais pour ton idée de l'add au compilé, c'est pas con, juste, bah comment faire mdr, je sais pas
il faudrait copier le .zip créé avec le dossier où l'installateur est présent

> Pour Github action, j'ai vu ce truc, mais vraiment, je suis une bille sur GitHub, t'as dû surement le remarquer mdr 
mdrr t'inquiète, je le suis un peu aussi ☠ ; faudrait simplement que j'apprenne à comment déjà compiler le projet, histoire de pouvoir le faire (n'hésite pas à venir DM sur discord, je te montrerais tout)

> Ensuite, pour le settings.json, ça j'ai pas trop compris, bon, je pense migrer les settings du registre vers un fichier, ça sera bien plus simple, pour éviter d'avoir des problèmes entre les comptes 
Tu as tout à fait raison !! (après faudra delete les règles du registre si jamais on désinstalle le logiciel), mais en gros il faudrait changer les règles du registre en fonction des paramètres que tu actives ou désactives sur le logiciel, cela évite de devoir rollback les modifications à la main

> Ensuite, pour le uninstall de Edge, c'est based sur le setup de Edge officiel, donc ça va c'est assez fiable
Nickel !
